spring:
  profiles:
    active: local
    include: oauth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/the-board?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.springframework.security: DEBUG
  org.hibernate.SQL: debug
# org.hibernate.type: trace